dodgercollector_project/urls.py
from django.contrib import admin
# Add the include function to the import
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # In this case '' represents the root route
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),

    # dodger urls
    path('dodgers/', views.dodgers_index, name='index'),
    path('dodgers/<int:dodger_id>/', views.dodgers_detail, name='detail'),
    path('dodgers/create/', views.DodgerCreate.as_view(), name='dodgers_create'),
    path('dodgers/<int:pk>/update/',
         views.DodgerUpdate.as_view(), name='dodgers_update'),
    path('dodgers/<int:pk>/delete/',
         views.DodgerDelete.as_view(), name='dodgers_delete'),
    path('dodgers/<int:dodger_id>/add_training/',
         views.add_training, name='add_training'),
    path('dodgers/<int:dodger_id>/assoc_equipment/<int:equipment_id>/',
         views.assoc_equipment, name='assoc_equipment'),
    path('dodgers/<int:dodger_id>/dissoc_equipment/<int:equipment_id>/',
         views.dissoc_equipment, name='dissoc_equipment'),
    path('dodgers/<int:dodger_id>/add_photo/',
         views.add_photo, name='add_photo'),

    # equipment urls
    path('equipments/', views.equipments_index, name='equipments_index'),
    path('equipments/<int:equipment_id>/',
         views.equipment_detail, name='equipment_detail'),
    path('equipments/create/', views.Create_Equipment.as_view(),
         name='equipments_create'),
    path('equipments/<int:pk>/update/',
         views.Update_equipment.as_view(), name='update_equipment'),
    path('equipments/<int:pk>/delete/',
         views.Delete_equipment.as_view(), name='delete_equipment'),

    # account urls
    path('accounts/signup/', views.signup, name='signup'),

]

main_app/models.py
from django.db import models

# Import the reverse function
from django.urls import reverse

from datetime import date

from django.contrib.auth.models import User


WORKOUTS = (
    ('W', 'Weight'),
    ('C', 'Cardio'),
    ('B', 'Batting'),
    ('P', 'Position Training')
)

# Create your models here.


class Equipment(models.Model):
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.name} {self.brand}'

    def get_absolute_url(self):
        return reverse('equipment_detail', kwargs={'equipment_id': self.id})

        class Meta:
            ordering = ['-date']


class Dodger(models.Model):
    name = models.CharField(max_length=100)
    position = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    salary = models.CharField(max_length=100)
    equipments = models.ManyToManyField(Equipment)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('detail', kwargs={'dodger_id': self.id})

    def trained_for_today(self):
        return self.training_set.filter(date=date.today()).count() >= len(WORKOUTS)


class Training(models.Model):
    date = models.DateField('training date')
    workout = models.CharField(
        max_length=1, choices=WORKOUTS, default=WORKOUTS[0][0])
    dodger = models.ForeignKey(Dodger, on_delete=models.CASCADE)

    def __str__(self):
        # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_workout_display()} on {self.date}"

    class Meta:
        ordering = ['-date']


class Photo(models.Model):
    url = models.CharField(max_length=200)
    dodger = models.ForeignKey(Dodger, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for dodger_id: {self.dodger_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Training


class TrainingForm(ModelForm):
    class Meta:
        model = Training
        fields = ['date', 'workout']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Dodger, Equipment, Photo
from .forms import TrainingForm

# Add the following import
from django.http import HttpResponse

import uuid
import boto3


S3_BASE_URL = 'https://s3-us-west-1.amazonaws.com/'
BUCKET = 'dodgercollector'


def home(request):
    return render(request, 'home.html')


def about(request):
    return render(request, 'about.html')


@login_required
def dodgers_index(request):
    dodgers = Dodger.objects.filter(user=request.user)
    return render(request, 'dodgers/index.html', {'dodgers': dodgers})


@login_required
def dodgers_detail(request, dodger_id):
    dodger = Dodger.objects.get(id=dodger_id)
    equipments_dodger_doesnt_have = Equipment.objects.exclude(
        id__in=dodger.equipments.all().values_list('id'))
    training_form = TrainingForm()
    return render(request, 'dodgers/detail.html', {
        'dodger': dodger, 'training_form': training_form,
        'equipments': equipments_dodger_doesnt_have
    })


@login_required
def add_training(request, dodger_id):
    form = TrainingForm(request.POST)
    if form.is_valid():
        new_training = form.save(commit=False)
        new_training.dodger_id = dodger_id
        new_training.save()
    return redirect('detail', dodger_id=dodger_id)


class DodgerCreate(LoginRequiredMixin, CreateView):
    model = Dodger
    fields = ['name', 'position', 'description', 'salary']
    success_url = '/dodgers/'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class DodgerUpdate(UpdateView):
    model = Dodger
    fields = ['position', 'description', 'salary']


class DodgerDelete(DeleteView):
    model = Dodger
    success_url = '/dodgers/'

# Equipments views


def equipments_index(request):
    equipments = Equipment.objects.all()
    context = {'equipments': equipments}

    return render(request, 'equipment/index.html', context)


def equipment_detail(request, equipment_id):
    equipment = Equipment.objects.get(id=equipment_id)
    context = {
        'equipment': equipment
    }
    return render(request, 'equipment/detail.html', context)


@login_required
def assoc_equipment(request, dodger_id, equipment_id):
    # Note that you can pass a equipment's id instead of the whole object
    Dodger.objects.get(id=dodger_id).equipments.add(equipment_id)
    return redirect('detail', dodger_id=dodger_id)


@login_required
def dissoc_equipment(request, dodger_id, equipment_id):
    # Note that you can pass a equipment's id instead of the whole object
    Dodger.objects.get(id=dodger_id).equipments.remove(equipment_id)
    return redirect('detail', dodger_id=dodger_id)


class Create_Equipment(CreateView):
    model = Equipment
    fields = '__all__'


class Update_equipment(UpdateView):
    model = Equipment
    fields = ['color']


class Delete_equipment(DeleteView):
    model = Equipment
    success_url = '/equipments/'


@login_required
def add_photo(request, dodger_id):
    # photo-file will be the "name" attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique "key" for S3 / needs image file extension too
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.'):]
        # just in case something goes wrong
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            # build the full url string
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            # we can assign to dodger_id or dodger (if you have a dodger object)
            photo = Photo(url=url, dodger_id=dodger_id)
            photo.save()
        except:
            print('An error occurred uploading file to S3')
    return redirect('detail', dodger_id=dodger_id)


def signup(request):
    error_message = ''
    if request.method == 'POST':
        # This is how to create a 'user' form object
        # that includes the data from the browser
        form = UserCreationForm(request.POST)
        if form.is_valid():
            # This will add the user to the database
            user = form.save()
            # This is how we log a user in via code
            login(request, user)
            return redirect('index')
        else:
            error_message = 'Invalid sign up - try again'
    # A bad POST or a GET request, so render signup.html with an empty form
    form = UserCreationForm()
    context = {'form': form, 'error_message': error_message}
    return render(request, 'registration/signup.html', context)

main_app/templates/dodgers/detail.html
{% extends 'base.html' %} {% block content %}

<h1>Dodger Details</h1>

<div class="row">
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ dodger.name }}</span>
        <p>Position: {{ dodger.position }}</p>
        <p>Description: {{ dodger.description }}</p>
        {% if dodger.salary %}
        <p>Salary: {{ dodger.salary }}</p>
        {% else %}
        <p>Salary: Unknown</p>
        {% endif %}
      </div>
      <div class="card-action">
        <a href="{% url 'dodgers_update' dodger.id %}">Edit</a>
        <a href="{% url 'dodgers_delete' dodger.id %}">Delete</a>
      </div>
    </div>
    {% for photo in dodger.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}" />
    {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <!-- new code below -->
    <form
      action="{% url 'add_photo' dodger.id %}"
      enctype="multipart/form-data"
      method="POST"
      class="card-panel"
    >
      {% csrf_token %}
      <input type="file" name="photo-file" />
      <br /><br />
      <input type="submit" class="btn" value="Upload Photo" />
    </form>
  </div>
  <div class="col s6">
    <form action="{% url 'add_training' dodger.id %}" method="post">
      {% csrf_token %} {{ training_form.as_p }}
      <input type="submit" class="btn" value="Add Training" />
    </form>
    <br />
    {% if dodger.trained_for_today %}
    <div class="card-panel teal-text center-align">
      {{dodger.name}} has done all workouts for today
    </div>
    {% else %}
    <div class="card-panel red-text center-align">
      {{dodger.name}} might need to do some workouts
    </div>
    {% endif %}
    <table class="striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Workout</th>
        </tr>
      </thead>
      <tbody>
        {% for training in dodger.training_set.all %}
        <tr>
          <td>{{training.date}}</td>
          <td>{{training.get_workout_display}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

<hr />
<div class="row">
  <div class="col s6">
    <h3>{{ dodger.name }}'s Equipments</h3>
    {% if dodger.equipments.count %} {% for equipment in dodger.equipments.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title"> A {{ equipment.brand }} {{ equipment.name }} </span>
      </div>
      <div class="card-action">
        <form action="{% url 'dissoc_equipment' dodger.id equipment.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn">Remove</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>No Equipments :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Equipments</h3>
    {% if equipments.count %} {% for equipment in equipments.all %}
    <div class="card">
      <div class="card-content">
        <span class="card-title"> A {{ equipment.brand }} {{ equipment.name }} </span>
      </div>
      <div class="card-action">
        <form action="{% url 'assoc_equipment' dodger.id equipment.id %}" method="post">
          {% csrf_token %}
          <button type="submit" class="btn">Add</button>
        </form>
      </div>
    </div>
    {% endfor %} {% else %}
    <h5>{{dodger.name}} Already Has All Equipments Available</h5>
    {% endif %}
  </div>
</div>

<script>
  var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true,
  });

  var selectEl = document.getElementById('id_workout');
  M.FormSelect.init(selectEl);
</script>
{% endblock %}

main_app/templates/dodgers/index.html
{% extends 'base.html' %} {% block content %}

<h1>Dodger List</h1>

{% for dodger in dodgers %}
<div class="card">
  <a href="/dodgers/{{ dodger.id }}">
    <div class="card-content">
      <span class="card-title">{{ dodger.name }}</span>
      <p>Position: {{ dodger.position }}</p>
      <p>Description: {{ dodger.description }}</p>
      {% if dodger.salary %}
      <p>Salary: $ {{ dodger.salary }}</p>
      {% else %}
      <p>Salary: unknown</p>
      {% endif %}
    </div>
  </a>
</div>
{% endfor %} {% endblock %}